name: validate

on:
  workflow_dispatch:
    inputs:
      revision:
        description: Git revision to validate
        required: false
        type: string
  workflow_call:
    inputs:
      revision:
        description: Git revision to validate
        required: true
        type: string

jobs:
  validate:
    name: Validate and test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout revision
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.revision || github.ref }}

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"

      - name: Type-check
        run: uvx hatch run dev-ci:type-check

      - name: Test and record coverage
        run: |
          rm -f coverage.xml
          uvx hatch run dev-ci:test --cov --cov-branch --cov-report=xml --cov-append

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
